### ISSUE TITLE
Add details in README

### ISSUE THREAD

**Issue by AndreiOrmanji** [ctf0/vscode-php-array-symbol-provider#1]
Currently it is not clear from description what this extension does. I've installed it but I did not see anything changed (i'm not trying to say this extension is useless, but I did not see any changes).

Can you provide more example how this extension works (screenshots or gif)?
This should definitely help other users to give it a try

**Comment by ctf0** [comment]
yeah i know what mean, its ok.

atm vscode have something call `go to symbol` https://code.visualstudio.com/docs/editor/editingevolved#_go-to-symbol
and this extension tries to add the same kind of information but for array keys ex.
- laravel config files which usually consists of array key & value

![image](https://github.com/ctf0/vscode-php-array-symbol-provider/assets/7388088/5990c371-a50c-4586-83db-e478f96eac88)

- also support for methods that return array ex.
```php
public function test() {
  return [
    'one' => 1,
    'two' => 2
  ];
}
```

> why would u use symbol navigation when u already have search ?

because its quicker & allow fuzzy search & navigate you directly to what u r looking for instead of plain text search

**Comment by AndreiOrmanji** [comment]
If you want, you can add screenshots like mine:
![image](https://github.com/ctf0/vscode-php-array-symbol-provider/assets/48985454/82a81dd0-96f6-49c9-96c3-f4e0dd72853f)

OR

![image](https://github.com/ctf0/vscode-php-array-symbol-provider/assets/48985454/e2944160-5b36-4db7-afb0-58a3008f2bea)

**Comment by ctf0** [comment]
can u plz make a PR with the changes needed?
